steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
#specify the name of the image
  args: ['build', '-t', 'gcr.io/$abinas-test-server/cb4a60f28246f', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$abinas-test-server/cb4a60f28246f']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
#specify the service name and the region
  args: ['run', 'deploy', 'laravel', '--image', 'gcr.io/$abinas-test-server/cb4a60f28246f', '--region', 'us-central1',         
        "--platform", "managed",
        "--port", "8000"]
images:
- gcr.io/$abinas-test-server/cb4a60f28246f

